### PR TITLE
[webhook] index a list of predefined attributes

### PR DESCRIPTION
**Pull request by williamchong**

### CODE REVIEW

**Review by makew0rld — CHANGES_REQUESTED** [review]
It seems unnecessary to have separate slices and separate calls to AA just for the indexed attributes. It would be simpler to combine them into just one slice, after all the `aa.PostKV` type is designed to support this.

**Comment by williamchong** [comment]
> It seems unnecessary to have separate slices and separate calls to AA just for the indexed attributes. It would be simpler to combine them into just one slice, after all the `aa.PostKV` type is designed to support this.

I though indexing is controlled by the query string `index=1`, is that not the case and i just need to set the type?

**Comment by makew0rld** [comment]
Sorry, the API is confusing. Even when `index=1` is set, the key is only indexed if it has a `type` set. So you can avoid indexing keys even with `index=1` by just not setting the `type` field. That is what I would recommend doing here.

**Comment by williamchong** [comment]
Rewrote the PR to always use `index=1` @makew0rld

**Pull request merged**
